CREATE DATABASE loms;
CREATE USER repl_user WITH PASSWORD 'repl_password';
GRANT CONNECT ON DATABASE loms TO repl_user;
\connect loms
GRANT SELECT ON ALL TABLES IN SCHEMA public TO repl_user;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO repl_user;
GRANT USAGE ON SCHEMA public TO repl_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO repl_user;